vre-hub/vre

- infrastructure/cluster/flux/cvmfs.yaml
- infrastructure/cluster/tf/jhub/config.yaml
- Add Flux CVMFS-CSI manifests (?) to manage the deployment of the new version of the CVMFS-CSI plugin
- Modify `tf` jhub configuration to add cvmfs volumes and extra volumes
> add flux script to manage cvmfs deployment

- infrastructure/cluster/flux-v2/jhub/jhub-release.yaml
Adding:
```
oidc_scope = openid profile offline_access
oidc_issuer = escape
auth_oidc_refresh_active true
auth_oidc_refresh_before_exp 20
```
To `rucio.cfg` for the user to try automatic token refresh by rucio itself (which is, however, independent of the plugin, which will still need the other token refresh mechanism).
> Add oidc params for token refresh

- infrastructure/cluster/flux-v2/jhub/jhub-release.yaml
Suggestion on the configuration.
Return var `RUCIO_OIDC_AUTH` to `file` (and add things to the corresponding place) rather than using `env`.
I have to be honest that I have ZERO idea if it's an improvement or not. Thoughts on this @goseind ?
> change oidc auth to file rather thanv env

- infrastructure/cluster/flux-v2/jhub/jhub-release.yaml
jhub raises an exception if certs are savec/read(?) on /certs. Changing to /tmp as in the escape-gitops clu
```bash
2023-08-02 08:35:37,826 ERROR   [Errno 13] Permission denied: '/certs/tmpcz30eab9'
2023-08-02 08:35:37,826 ERROR
Rucio exited with an unexpected/unknown error.
Please rerun the last command with the "-v" option to gather more information.
If you're sure there is a problem with Rucio itself, please follow up at: https://github.com/rucio/rucio/issues
```
> change certs dir to /tmp

- infrastructure/cluster/flux-v2/cvmfs/cvmfs.yaml
Needed so that the cluster could fully erase the PV and PVC correctly.
Mental note for the future: There is no need of deleting the PV and PVC in case of CVMFS being re deployed.
> reapplying cvmfs pv, pvc and pod

- infrastructure/cluster/flux-v2/jhub/jhub-release.yaml
The token needs to be stored in the format `oauth2:${REFRESH_TOKEN}:iam-escape.cloud.cnaf.infn.it/userinfo` according to: https://eos-docs.web.cern.ch/diopside/manual/using.html#oauth2-for-authentication
> add logic for eos oauth2 token

- infrastructure/cluster/flux-v2/jhub/jhub-release.yaml
This change uses the access token directly from the auth state of jhub to pass it on as an env var to be used by rucio and eos.
> Use access token directly from auth state

- infrastructure/cluster/flux-v2/jhub/jhub-release.yaml
This PR removes parameters from the `rucio.cfg` that might cause the CLI to refresh the token unintentionally and sets the extension to use the token directly from the environment variable.
> Remove values from rucio.cfg

- infrastructure/cluster/flux-v2/jhub/jhub-release.yaml
Ref #218 
the `oidc_polling = true` avoids copying back to the jhub terminal the token provided. 
@goseind @egazzarr why we took out the following args from the rucio cfg file ?
```
oidc_scope = openid profile offline_access
oidc_issuer = escape
auth_oidc_refresh_active = true
auth_oidc_refresh_before_exp = 20
```
> avoid copying back the token to the jhub instance

- containers/base-ops/Dockerfile
- containers/eos-fuse-mount/Dockerfile
- containers/rucio-client/Dockerfile
as old one expired and no certificates were copied in the containers
> changing link of EGI trustanchors 

- infrastructure/cluster/flux-v2/jhub/jhub-release.yaml
In order for the Rucio extension to be compatible with Dask, an image has been added to the `jhub-profile-cm.yaml`. Once the user selects this image, he/she is able to see the Rucio extension (jupyter-server-proxy v3) along with a dask extension (which is also a bit older than the latest one, as we need jupyter-server-proxy v3). 
In order to test that the extension of Dask works, you can open a notebook and try to run:
```
import dask
import dask.distributed
from dask_gateway import Gateway
from dask_gateway import GatewayCluster
import dask.array as da
import requests
from dask_gateway import scheduler_preload
import os
gateway = Gateway()
gateway.list_clusters()
gateway.new_cluster()
```
Normally, with this edit to the jupyterhub helm release, you do not need to import any variables, …
> adding dask config in jupyterhub helm chart 

- infrastructure/cluster/flux-v2/jhub/jhub-release.yaml
flux message:
```bash
jhub            helmrelease/jhub-cvre           2.0.0           False           False   Helm upgrade failed: values don't meet the specifications of the schema(s) in the following chart(s):
jupyterhub:                                                                                          
- singleuser: Additional property volumes is not allowed                                             
- singleuser.image: Additional property volumeMounts is not allowed                                  
```
> fix flux sync

- infrastructure/cluster/flux-v2/jhub/jhub-release.yaml
Latest upstream images raise the following error
```
Leave $JUPYTERHUB_SINGLEUSER_APP unspecified (or use the default JUPYTERHUB_SINGLEUSER_APP=jupyter-server), and set `c.Spawner.default_url = "/tree"` to make notebook v7 the default UI.
```
Testing if config is compatible with old setup
> Update jhub config

- infrastructure/cluster/flux-v2/jhub/jhub-release.yaml
error message: `fix traitlets.traitlets.TraitError: 3.5Gi is not a valid memory specification. Must be an int or a string with suffix K, M, G, T`
> fix PR#275

- infrastructure/cluster/flux-v2/jhub/jhub-release.yaml
Will install version `jupyterhub==4.1.5` (https://hub.jupyter.org/helm-chart/)
> Update jhub-release.yaml to chart v3.3.7

- infrastructure/cluster/flux-v2/reana/reana-ingress.yaml
- infrastructure/cluster/flux-v2/reana/reana-release.yaml
When deleting the reana Chart, PV and PVC will be shown as `terminating`.
To fully kill them do `kubectl patch pvc {PVC_NAME} -p '{"metadata":{"finalizers":null}}'`
> reapply reana helm charts with new minor v 0.9.3

- infrastructure/cluster/flux/jhub/jhub-release.yaml
- infrastructure/scripts/jhub_secrets.sh
- infrastructure/secrets/jhub/ss_jhub-vre-auth-state.yaml
The secrets has been already applied to the cluster
> change jhub auth_state

- infrastructure/cluster/flux/jhub/jhub-release.yaml
cf: #289 (@Soap2G )
`extraEnvFrom` should be indented with `config`
> hotfix:PR289

- .github/workflows/merge-check-always.yml
- .github/workflows/merge-check-paths.yml
TF is no longer used - since the cluster upgrade, where all the flux sync was also move to `infrastructure/cluster/flux`.
Closes #163 and #229
> remove terraform CI checks and change flux folder

- containers/rucio-noise/produce_noise.sh
Change the looping and verbosity to
```bash
for (( i=1; i<=$len; i++ )); do
echo '*** '"${rses[$i]}"''
echo '*** rucio upload to '"${rses[$i]}"''
for (( j=1; j<=$len; j++ )); do
if [ $i != $j ]; then
echo '*** transfer from '"${rses[$i]}"' to '"${rses[$j]}"''
fi
done
done
```
> improve verbosity and loops of rucio noise container

- infrastructure/cluster/flux/jhub/jhub-release.yaml
> fix: ISSUE #313 add podSecurityContext to avoid recursive chmod on storage mount
