adm/rucio-client.yaml
iac/tf/cluster/main-helm.tf
iac/tf/cluster/rucio/values-daemons.yaml

daemons to v 1.30.4, DB pool max size to 100 and fts-cron certificates referenced correctly

rucio dev 

---

infrastructure/cluster/tf/jhub/config.yaml
infrastructure/cluster/tf/main-helm.tf

adds `jhub` with config for `rucio-extension`, applied and tested in the cluster
ref https://github.com/vre-hub/vre/issues/68

tf jhub with rucio-extension config

---

.github/workflows/docker-rucio-noise.yml
containers/rucio-noise/Dockerfile

Rebuild rucio nose (update ssl certs)

---

.gitignore

mainly for the `tmp_local_secrets` dir !

update .gitignore with new dir structure 

---

.github/workflows/docker-iam-rucio-sync.yaml
.github/workflows/docker-rucio-noise.yaml
containers/iam-rucio-sync/Dockerfile
containers/rucio-noise/Dockerfile
infrastructure/cluster/flux-v2/rucio-vre/rucio-cronjobs.yaml

And add building time LABEL and

set :latest version on cronjobs for idealgitops

---

infrastructure/cluster/flux-v2/jhub/jhub-profiles-cm.yaml

To debug rucio plugin OIDC auth against the new image build.

Add debug image to jhub profiles

---

infrastructure/cluster/flux-v2/cvmfs/cvmfs.yaml

Add namespace to pod deployed with cvmfs installation

Fix PR#178 -  ns_cvmfs_pod

---

infrastructure/cluster/flux-v2/cvmfs/cvmfs.yaml

Taking resources out temporarily

cvmfs PV and PVC were deleted by hand but are stuck. 

---

infrastructure/cluster/flux-v2/jhub/jhub-release.yaml

Way to proceed in the future 
- Add the pvc and pv to helm 
- Add the volumes and extra volumes to jhub
- finally deploy cvmfs using helm

add again the cvmfs volumens

---

infrastructure/cluster/flux-v2/jhub/jhub-profiles-cm.yaml

Needs https://github.com/vre-hub/environments/actions/runs/5760428055/job/15616381231 to be finished first

add ROOT env to jhub config map

---

infrastructure/cluster/flux-v2/eos/eosfuse-daemonset.yaml

Fix PR#207: Fix spec of eosfuse Daemonset

---

containers/iam-reana-sync/add_reana_users.py

add as new users only the users that are not registered in reana.
Haven't found a more efficient way to iterate through the `requests.get` answer.

Export users from reana and compare list to users from IAM

---

.github/workflows/docker-iam-reana-sync.yaml
containers/iam-reana-sync/.dockerignore
containers/iam-reana-sync/Dockerfile
containers/iam-reana-sync/README.md
containers/iam-reana-sync/add_reana_users.py
containers/iam-reana-sync/generate_email_list.py
containers/iam-reana-sync/requirements.txt
infrastructure/cluster/flux-v2/reana/reana-iam-cronjob.yaml

and grant them an access token automatically

container and cronjob to automatically add IAM users to Reana DB

---

infrastructure/cluster/flux-v2/jhub/jhub-profiles-cm.yaml

Needs https://github.com/vre-hub/environments/actions/runs/6322937756/job/17169506311 to be finished first

Add microomega env

---

infrastructure/cluster/flux-v2/jhub/jhub-profiles-cm.yaml

Ref: https://github.com/vre-hub/environments/pull/39

add dev env

---

infrastructure/cluster/flux-v2/jhub/jhub-release.yaml

Solves #213 and #207.
Related with #253

clean and rename EOS mounting points

---

infrastructure/cluster/flux-v2/jhub/jhub-release.yaml

fix path or eos fuse mounted volumes

---

.github/workflows/docker-autobuild-release.yaml

Ref. #259 
fixes:
- wrong syntax (matrix elements) 
- wait second step to start step until first hasn't finished.

fix PR#259

---

containers/README.md
containers/rucio-client/Dockerfile

- And updated `reana-client==0.9.2`

change rucio-client dockerfile back to rucio s clients base image

---

infrastructure/cluster/flux-v2/jhub/jhub-release.yaml

Same error as #271 
this time 
```bash
jupyterhub:                                                                                          
- singleuser: Additional property volumes is not allowed
```

fix flux sync 2

---

infrastructure/cluster/flux-v2/reana/reana-iam-cronjob.yaml

re apply reana cronjobs

---

infrastructure/cluster/flux-v2/jhub/jhub-release.yaml
infrastructure/cluster/manual/node_and_tolerations_jup.yaml

and add snippet to add/remove node selection and tolerations (previously applied to eosxd and cvmfs daemonsets)

Remove tolerations jup

---

infrastructure/cluster/flux/rucio/rucio-cronjobs.yaml

rucio identification IS needed as we are managing users
cf: #291

hotfix:PR291

---

infrastructure/cluster/flux/jhub/jhub-release.yaml

Changing pull policy to cache images

---

containers/rucio-noise/produce_noise.sh

all in the title :harold:
c.f: #305

forgot to end if in produce_noise.sh

---

containers/rucio-noise/produce_noise.sh

hotfix:PR305-306

---

infrastructure/cluster/flux/jhub/jhub-release.yaml

Build on https://github.com/vre-hub/environments/commit/ee63437db3027435207a527d1f06ae774363d046 and https://github.com/vre-hub/environments/actions/runs/16834726384

feat: update Default env with rucio-jupyterlab 1.3.1 and reana-jupyterlab 1.0.1
